# Generated by Django 6.0.3 on 2026-03-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='plan',
            field=models.CharField(choices=[('FREE', 'Free'), ('PRO', 'Pro')], default='FREE', max_length=10),
        ),
    ]
