# Generated by Django 5.1.4 on 2026-07-24 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_company_expiry_date_task_due_date_alter_company_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('PROJECT_CREATED', 'Project created'), ('PROJECT_DELETED', 'Project deleted'), ('TASK_CREATED', 'Task created'), ('USER_ADDED', 'User added'), ('PLAN_UPGRADED', 'Plan changed')], max_length=30)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='accounts.company')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
